[2022-02-12 18:08:11,249] INFO Expiring session 0x10004ff6c8f0009, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2022-02-12 18:08:11,680] INFO Expiring session 0x10004ff6c8f000a, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2022-02-12 18:08:11,145] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Disconnecting from node 0 due to request timeout. (org.apache.kafka.clients.NetworkClient)
[2022-02-12 18:08:11,180] WARN Client session timed out, have not heard from server in 56462ms for session id 0x10004ff6c8f0009 (org.apache.zookeeper.ClientCnxn)
[2022-02-12 18:08:11,892] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Cancelled in-flight FETCH request with correlation id 34008 due to node 0 being disconnected (elapsed time since creation: 4227384ms, elapsed time since send: 4227384ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient)
[2022-02-12 18:08:12,129] WARN Session 0x10004ff6c8f0009 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 56462ms for session id 0x10004ff6c8f0009
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
[2022-02-12 18:08:12,179] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Client requested connection close from node 0 (org.apache.kafka.clients.NetworkClient)
[2022-02-12 18:08:12,199] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=892605620, epoch=18084) to node 0: (org.apache.kafka.clients.FetchSessionHandler)
java.io.IOException: Connection to 0 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-12 18:08:12,282] WARN [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=1, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={}, isolationLevel=READ_UNCOMMITTED, removed=, replaced=, metadata=(sessionId=892605620, epoch=18084), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 0 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:99)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:109)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:219)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:322)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:136)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2022-02-12 18:08:13,585] INFO Opening socket connection to server localhost/127.0.0.1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-02-12 18:08:13,611] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-12 18:08:13,611] INFO Socket connection established, initiating session, client: /127.0.0.1:49247, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2022-02-12 18:08:13,628] INFO Invalid session 0x10004ff6c8f0009 for client /127.0.0.1:49247, probably expired (org.apache.zookeeper.server.ZooKeeperServer)
[2022-02-12 18:08:13,630] WARN Unable to reconnect to ZooKeeper service, session 0x10004ff6c8f0009 has expired (org.apache.zookeeper.ClientCnxn)
[2022-02-12 18:08:13,630] WARN Session 0x10004ff6c8f0009 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x10004ff6c8f0009 has expired
	at org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1434)
	at org.apache.zookeeper.ClientCnxnSocket.readConnectResult(ClientCnxnSocket.java:154)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:86)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-02-12 18:08:13,631] INFO EventThread shut down for session: 0x10004ff6c8f0009 (org.apache.zookeeper.ClientCnxn)
[2022-02-12 18:08:13,632] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2022-02-12 18:08:13,638] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2022-02-12 18:08:13,640] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@6ebf0f36 (org.apache.zookeeper.ZooKeeper)
[2022-02-12 18:08:13,647] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2022-02-12 18:08:13,653] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[2022-02-12 18:08:13,657] INFO Opening socket connection to server localhost/127.0.0.1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-02-12 18:08:13,657] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2022-02-12 18:08:13,657] INFO Socket connection established, initiating session, client: /127.0.0.1:49248, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2022-02-12 18:08:13,864] INFO Session establishment complete on server localhost/127.0.0.1:2181, session id = 0x10004ff6c8f000b, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2022-02-12 18:08:13,906] INFO Updated cache from existing FinalizedFeaturesAndEpoch(features=Features{}, epoch=0) to latest FinalizedFeaturesAndEpoch(features=Features{}, epoch=0). (kafka.server.FinalizedFeatureCache)
[2022-02-12 18:08:14,103] INFO Invalid session 0x10004ff6c8f000a for client /0:0:0:0:0:0:0:1:49266, probably expired (org.apache.zookeeper.server.ZooKeeperServer)
[2022-02-12 18:08:14,703] INFO Creating /brokers/ids/1 (is it secure? false) (kafka.zk.KafkaZkClient)
[2022-02-12 18:08:14,894] INFO Stat of the created znode at /brokers/ids/1 is: 290,290,1644669494722,1644669494722,1,0,0,72063089122410507,202,0,290
 (kafka.zk.KafkaZkClient)
[2022-02-12 18:08:14,918] INFO Registered broker 1 at path /brokers/ids/1 with addresses: PLAINTEXT://localhost:9093, czxid (broker epoch): 290 (kafka.zk.KafkaZkClient)
